100-hours-a-week/13-Cafeboo-BE

build.gradle
src/main/resources/application.properties

빌드 파일, application.properties 수정
- Oauth, jwt, 관련 의존성 변경
- 데이터베이스 의존성 수정
- 대면으로 리뷰 진행하였습니다.

✏️Chore: 설정 파일 수정

---

src/main/java/com/ktb/cafeboo/domain/auth/controller/AuthController.java
src/main/java/com/ktb/cafeboo/domain/auth/dto/AuthDTO.java
src/main/java/com/ktb/cafeboo/domain/auth/dto/KakaoLoginRequest.java
src/main/java/com/ktb/cafeboo/domain/auth/dto/KakaoLoginResponse.java
src/main/java/com/ktb/cafeboo/domain/auth/dto/KakaoTokenResponse.java
src/main/java/com/ktb/cafeboo/domain/auth/dto/KakaoUserResponse.java
src/main/java/com/ktb/cafeboo/domain/auth/infra/KakaoTokenClient.java
src/main/java/com/ktb/cafeboo/domain/auth/infra/KakaoUserClient.java
src/main/java/com/ktb/cafeboo/domain/auth/model/AuthModel.java
src/main/java/com/ktb/cafeboo/domain/auth/repository/AuthRepository.java
src/main/java/com/ktb/cafeboo/domain/auth/service/AuthService.java
src/main/java/com/ktb/cafeboo/domain/auth/service/KakaoOauthService.java
src/main/java/com/ktb/cafeboo/domain/user/model/User.java
src/main/java/com/ktb/cafeboo/domain/user/model/UserAlarmSetting.java
src/main/java/com/ktb/cafeboo/domain/user/model/UserCaffeinInfo.java
src/main/java/com/ktb/cafeboo/domain/user/model/UserFavoriteDrinks.java
src/main/java/com/ktb/cafeboo/domain/user/model/UserHealthInfo.java
src/main/java/com/ktb/cafeboo/domain/user/model/UserModel.java
src/main/java/com/ktb/cafeboo/domain/user/repository/UserRepository.java
src/main/java/com/ktb/cafeboo/global/config/SecurityConfig.java
src/main/java/com/ktb/cafeboo/global/enums/LoginType.java
src/main/java/com/ktb/cafeboo/global/enums/UserRole.java
src/main/java/com/ktb/cafeboo/global/security/JwtProvider.java

- auth 도메인 내 controller, service, infra, dto 패키지 수정
- user 도메인 내 model, repository 수정
- 인증/인가 과정 코드 흐름을 봐주시고, 이해가 안되신다면 말씀해주세요

카카오 소셜 로그인/회원가입 기능 개발

---

src/main/java/com/ktb/cafeboo/domain/caffeinediary/repository/CaffeineResidualRepository.java
src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineResidualService.java
src/main/java/com/ktb/cafeboo/domain/report/controller/MonthlyReportController.java
src/main/java/com/ktb/cafeboo/domain/report/controller/WeeklyReportController.java
src/main/java/com/ktb/cafeboo/domain/report/controller/YearlyReportController.java
src/main/java/com/ktb/cafeboo/domain/report/dto/MonthlyCaffeineReportResponse.java
src/main/java/com/ktb/cafeboo/domain/report/dto/YearlyCaffeineReportResponse.java
src/main/java/com/ktb/cafeboo/domain/report/model/DailyStatistics.java
src/main/java/com/ktb/cafeboo/domain/report/model/MonthlyReport.java
src/main/java/com/ktb/cafeboo/domain/report/model/WeeklyReport.java
src/main/java/com/ktb/cafeboo/domain/report/model/YearlyReport.java
src/main/java/com/ktb/cafeboo/domain/report/repository/DailyStatisticsRepository.java
src/main/java/com/ktb/cafeboo/domain/report/repository/MonthlyReportRepository.java
src/main/java/com/ktb/cafeboo/domain/report/repository/WeeklyReportRepository.java
src/main/java/com/ktb/cafeboo/domain/report/repository/YearlyReportRepository.java
src/main/java/com/ktb/cafeboo/domain/report/service/DailyStatisticsService.java
src/main/java/com/ktb/cafeboo/domain/report/service/MonthlyReportService.java
src/main/java/com/ktb/cafeboo/domain/report/service/WeeklyReportService.java
src/main/java/com/ktb/cafeboo/domain/report/service/YearlyReportService.java

- https://github.com/100-hours-a-week/13-Cafeboo-BE/pull/16
- https://github.com/100-hours-a-week/13-Cafeboo-BE/pull/18
- 월간, 주간 리포트 조회와 관련된 내용 report 도메인에 추가
- 기존에 push 했던 파일들에 대해 오류 수정 및 기획에 맞게 리팩토링 진행
- 각 기능 별로 흐름 위주로 체크 해주세요.
- API Response의 경우 PR의 merge 진행 후 새로운 branch 파서 수정 진행하겠습니다.
- postman을 활용한 수동 API 요청, dataGrip을 활용한 db 변경 사항 조회

✨ feat : 월간/연간 리포트 조회 기능 구현

---

src/main/java/com/ktb/cafeboo/global/security/JwtProvider.java
src/main/java/com/ktb/cafeboo/global/util/AuthChecker.java

- ownerId와 currentUserId를 비교하여 권한 없는 접근 시 예외 발생
- 리소스 기반 인가 로직을 공통 유틸로 분리하여 재사용성 향상
- 리소스 접근(인가) 관리를 위한 기본 클래스 추가하였습니다.

✨feat: 리소스 소유자 확인을 위한 AuthChecker 유틸 클래스 추가

---

src/main/java/com/ktb/cafeboo/domain/drink/repository/CafeRepository.java
src/main/java/com/ktb/cafeboo/domain/drink/repository/DrinkRepository.java
src/main/java/com/ktb/cafeboo/domain/drink/repository/DrinkSizeNutritionRepository.java
src/main/java/com/ktb/cafeboo/domain/drink/service/CafeService.java
src/main/java/com/ktb/cafeboo/domain/drink/service/DrinkService.java

dev 브랜치에서 작업 시 TransientPropertyValueException 오류 발생에 따른 service, repository 로직 추가
- Drink 도메인 관련 service, repository 추가
- 디스코드로 리뷰 진행 완료

✏️Chore: Drink 도메인 service, repository 추가

---

src/main/java/com/ktb/cafeboo/global/config/WebConfig.java

- global/config 패키지 WebConfig 클래스 생성

feat: WebConfig 구성 및 CORS 설정

---

src/main/java/com/ktb/cafeboo/domain/caffeinediary/controller/CaffeineIntakeController.java
src/main/java/com/ktb/cafeboo/domain/caffeinediary/dto/CaffeineIntakeRequest.java
src/main/java/com/ktb/cafeboo/domain/caffeinediary/dto/CaffeineIntakeResponse.java
src/main/java/com/ktb/cafeboo/domain/caffeinediary/dto/DailyCaffeineDiaryResponse.java
src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineIntakeService.java

- DailyCaffeineDiaryResponse DTO에 drinkId 필드 추가
- DTO 에 ID 타입 String으로 변경
-  ID 값들은 String 으로 처리하는 상세 이유는 api 명세 참고해주세요
- Postman 및 로컬 데이터베이스로 테스트

✨feat: DailyCaffeineDiaryResponse DTO에 drinkId 필드 추가 및 ID 타입 String으로 변경

---

src/main/java/com/ktb/cafeboo/global/config/SecurityConfig.java
src/main/java/com/ktb/cafeboo/global/infra/ai/dto/PredictCaffeineLimitByRuleRequest.java

- SecurityConfig 클래스 내 CorsConfigurationSource 빈 등록
- PredictCaffeineLimitByRuleRequest 클래스 수정
- 현재 인공지능 서버 배포 작업 중이셔서 실제 호출 테스트는 진행하지 못했습니다.
- 로그로 출력해보았을때, 응답과 요청 바디가 명세와 일치함을 확인하였습니다

인공지능 서버 요청 DTO 수정 및 CORS 설정 추가

---

src/main/java/com/ktb/cafeboo/global/config/SecurityConfig.java

- SecurityConfig내 securityFilterChain 수정

hotfix: Spring Security 필터 체인에 CORS 필터를 추가

---

src/main/java/com/ktb/cafeboo/domain/auth/service/KakaoOauthService.java
src/main/java/com/ktb/cafeboo/domain/user/model/UserAlarmSetting.java
src/main/java/com/ktb/cafeboo/domain/user/service/UserService.java

- KakaoOauthService 내 login 메서드 수정
-

🐛fix: 알람 설정 기본 생성 및 온보딩 체크 로직 수정

---

src/main/java/com/ktb/cafeboo/domain/auth/service/KakaoOauthService.java
src/main/java/com/ktb/cafeboo/domain/drink/repository/DrinkSizeNutritionRepository.java
src/main/java/com/ktb/cafeboo/domain/drink/service/DrinkService.java
src/main/java/com/ktb/cafeboo/domain/user/dto/UserAlarmSettingCreateRequest.java
src/main/java/com/ktb/cafeboo/global/apiPayload/exception/ApiExceptionHandler.java
src/main/java/com/ktb/cafeboo/global/config/SecurityConfig.java

- 유저 알람설정 기본값 설정 비즈니스 로직 수정
- 음료 섭취 조회 시, 영양성분 조회 repository 메서드 수정

🐛fix: 소셜 로그인 오류 및 음료 섭취 등록 오류

---

src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineResidualService.java
src/main/java/com/ktb/cafeboo/domain/report/controller/WeeklyReportController.java
src/main/java/com/ktb/cafeboo/domain/report/service/DailyReportService.java
src/main/java/com/ktb/cafeboo/domain/report/service/WeeklyReportScheduler.java
src/main/java/com/ktb/cafeboo/global/infra/ai/client/AiServerClient.java
src/main/java/com/ktb/cafeboo/global/infra/ai/dto/CreateWeeklyReportRequest.java

- AI 요청, 응답 형식 변경에 따른 내용 수정
- 섭취 내역 조회 시 KST 기준 설정 및 로그 추가
- X

🐛Fix: AI 요청, 응답 형식 변경에 따른 내용 수정 및 섭취 내역 조회 시간 기준 한국 시간 (KST) 기준으로 설정

---

src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineResidualService.java
src/main/java/com/ktb/cafeboo/domain/report/service/DailyReportService.java

디버깅용 로그 출력 부분 삭제
- 불필요한 로그가 쌓임에 따른 log.info 부분 삭제
- X

🔥Remove: 디버깅용 로그 출력 부분 삭제

---

.idea/dataSources.xml
src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineIntakeService.java
src/main/java/com/ktb/cafeboo/domain/report/model/MonthlyReport.java
src/main/java/com/ktb/cafeboo/domain/report/model/WeeklyReport.java
src/main/java/com/ktb/cafeboo/domain/report/model/YearlyReport.java
src/main/java/com/ktb/cafeboo/domain/report/service/DailyStatisticsService.java
src/main/java/com/ktb/cafeboo/domain/report/service/WeeklyReportService.java

- 엔티티 참조 관계 수정
- dailyStatistics null 일 때 예외 처리  
- X

🐛Fix: 오류 수정

---

src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineIntakeService.java

PATCH 로그 추가

---

src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineIntakeService.java

request의 ID null 일 시 예외 처리 추가
- request의 ID null 일 시 예외 처리 추가
- X

✏️Chore: request의 ID null 일 시 예외 처리 추가

---

src/main/java/com/ktb/cafeboo/domain/report/service/WeeklyReportService.java

- n주차 정보 반영 수정
- X
- 재배포 후 확인 예정

✏️Chore: n주차 정보 반영 수정

---

src/main/java/com/ktb/cafeboo/domain/auth/controller/AuthController.java
src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineIntakeService.java

- 세미콜론 삭제, 응답 상태 코드 변경
- FE 요청에 따른 303 SEE OTHER -> 204 NO CONTENT로 응답 변경

🎨Style: 세미콜론 삭제, 응답 상태 코드 변경

---

src/main/java/com/ktb/cafeboo/domain/auth/controller/AuthController.java
src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineIntakeService.java

Reverts 100-hours-a-week/13-Cafeboo-BE#72

Revert "🎨Style: 세미콜론 삭제, 응답 상태 코드 변경"

---

src/main/java/com/ktb/cafeboo/global/enums/DrinkSize.java

enum에 믹스 커피 사이즈 Stick 추가
- enum에 사이즈 Stick 추가 
- 대면으로 리뷰 진행했습니다.

hotfix: 음료 사이즈 추가

---

src/main/java/com/ktb/cafeboo/domain/caffeinediary/repository/CaffeineResidualRepository.java

- 잔존량 데이터 조회 시 섭취 시간 기준 오름차순 정렬
- X

Fix: 잔존량 데이터 조회 시 섭취 시간 기준 오름차순 정렬

---

src/main/java/com/ktb/cafeboo/CafebooApplication.java
src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineIntakeService.java
src/main/java/com/ktb/cafeboo/domain/report/service/ReportService.java
src/main/java/com/ktb/cafeboo/domain/report/service/WeeklyReportScheduler.java

- 사용하지 않는 파일 삭제 및 Null Pointer Exception 대응 부분 추가.
- X

🐛Fix: NullPointer Exception 수정

---

src/main/java/com/ktb/cafeboo/domain/report/service/WeeklyReportScheduler.java

- userWakeUpTime에 wakeUpTime 관련 정보를 가져와서 사용하도록 수정
- 유저 카페인 정보가 없는 경우 default 값인 400을 사용하도록 내용 수정
- X

🐛Fix: NPE 발생 부분 내용 수정

---

build.gradle
src/main/java/com/ktb/cafeboo/domain/report/controller/MonthlyReportController.java
src/main/java/com/ktb/cafeboo/domain/report/controller/WeeklyReportController.java
src/main/java/com/ktb/cafeboo/domain/report/dto/MonthlyCaffeineReportResponse.java
src/main/java/com/ktb/cafeboo/domain/report/service/WeeklyReportService.java
src/main/java/com/ktb/cafeboo/global/config/SecurityConfig.java
src/main/java/com/ktb/cafeboo/global/config/SwaggerConfig.java

- Swagger 관련 의존성 및 Info 파일 추가
- FE와의 매핑 오류가 있던 MonthlyReportResponse에서의 오타 수정
- MonthlyReportResponse 관련해서 보고 알려주세요.

Feat: Swagger 추가 및 마이너한 오류 수정

---

src/main/java/com/ktb/cafeboo/domain/caffeinediary/controller/CaffeinediaryController.java
src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineIntakeService.java
src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineResidualService.java
src/main/java/com/ktb/cafeboo/domain/report/controller/WeeklyReportController.java
src/main/java/com/ktb/cafeboo/domain/report/service/WeeklyReportScheduler.java
src/main/java/com/ktb/cafeboo/domain/report/service/WeeklyReportService.java
src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/ErrorStatus.java
src/main/java/com/ktb/cafeboo/global/infra/ai/dto/CreateWeeklyAnalysisRequest.java
src/main/java/com/ktb/cafeboo/global/infra/ai/dto/ReceiveWeeklyAnalysisRequest.java

- CreateWeeklyAnalysisRequest DTO에 필드 추가. (현재 @JsonProperty로 난잡하게 선언되어 있는 부분 추후 수정 예정)
- WeeklyReportScheduler.java에 DTO에 필드 추가됨에 따른 NPE 회피를 위한 예외 처리 기능 추가
- 보고 이해되지 않는 부분 있다면 코멘트 남겨주세요.
- dev branch에 merge 후 dev 서버에서 실행해 확인할 예정입니다.

Refactor: 주간 섭취 내역 평가 기준 추가에 따른 구조 수정

---

docs/logging-convention.md
src/main/java/com/ktb/cafeboo/domain/ai/service/CaffeineRecommendationService.java
src/main/java/com/ktb/cafeboo/domain/auth/controller/AuthController.java
src/main/java/com/ktb/cafeboo/domain/auth/service/AuthService.java
src/main/java/com/ktb/cafeboo/domain/auth/service/KakaoOauthService.java
src/main/java/com/ktb/cafeboo/domain/caffeinediary/controller/CaffeineIntakeController.java
src/main/java/com/ktb/cafeboo/domain/caffeinediary/controller/CaffeinediaryController.java
src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineIntakeService.java
src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineResidualService.java
src/main/java/com/ktb/cafeboo/domain/report/controller/DailyReportController.java
src/main/java/com/ktb/cafeboo/domain/report/controller/MonthlyReportController.java
src/main/java/com/ktb/cafeboo/domain/report/controller/WeeklyReportController.java
src/main/java/com/ktb/cafeboo/domain/report/controller/YearlyReportController.java
src/main/java/com/ktb/cafeboo/domain/report/repository/ReportRepository.java
src/main/java/com/ktb/cafeboo/domain/user/controller/UserController.java
src/main/java/com/ktb/cafeboo/domain/user/service/UserAlarmSettingService.java
src/main/java/com/ktb/cafeboo/domain/user/service/UserCaffeineInfoService.java
src/main/java/com/ktb/cafeboo/domain/user/service/UserHealthInfoService.java
src/main/java/com/ktb/cafeboo/domain/user/service/UserService.java
src/main/java/com/ktb/cafeboo/global/logging/LoggingMdcFilter.java
src/main/resources/logback-spring.xml

- 컨트롤러, 서비스 계층 내 주요 로직에 log.info, log.warn, log.error 등의 로그 메서드 적용
- `LoggingMdcFilter` 클래스 추가: 요청마다 userId, requestId MDC에 자동 주입
- logback-spring.xml 수정:기존 스프링 부트 기본 포맷 유지하면서 userId, requestId를 MDC 기반으로 추가 출력
- try-catch 구문 추가한 곳 있지만, 그 외에는 리팩토링 없이 작성
- 컨벤션 문서 참고 하셔서 리포트 및 ai 호출 서비스 로깅 작성하고 pr 주세요
Fixes #88

[REFACTOR] 로깅 추가하기: 서비스 진행 상황과 오류 로그 추가 

---

src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/ChatController.java
src/main/java/com/ktb/cafeboo/domain/coffeechat/model/CoffeeChat.java
src/main/java/com/ktb/cafeboo/domain/coffeechat/model/CoffeeChatMember.java
src/main/java/com/ktb/cafeboo/domain/coffeechat/model/CoffeeChatMessage.java
src/main/java/com/ktb/cafeboo/domain/coffeechat/repository/CoffeeChatMessageRepository.java
src/main/java/com/ktb/cafeboo/domain/coffeechat/service/ChatService.java
src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatMessageService.java

- Builder 사용 시 리스트 필드 null 문제 해결을 위한 @Builder.Default 추가
- CoffeeChatMember 엔티티 필드명 변경 
- x

[FIX] 커피챗 도메인 버그 수정

---

src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/CoffeeChatCreateResponse.java
src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/CoffeeChatDetailResponse.java
src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/CoffeeChatListResponse.java

- `CoffeeChatCreateResponse`, `CoffeeChatDetailResponse`, `CoffeeChatSummary` DTO 필드명 `coffeChatId` -> `coffeeChatId` 수정
- x
- 직접 테스트한 방법/결과 적기

[FIX]: DTO 필드 오타 수정

---

src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/StompMessagePublish.java
src/main/java/com/ktb/cafeboo/domain/coffeechat/repository/CoffeeChatMemberRepository.java
src/main/java/com/ktb/cafeboo/domain/coffeechat/service/ChatService.java

- FE에서 사용하는 필드가 사용될 수 있도록 내용 DTO 및 사용 repository 수정
- 코멘트 남겨주세요
- FE 연동을 통한 로컬 환경에서 테스트 진행

[FIX] 메시지 전송 간 오류 수정

---

src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/StompMessagePublish.java
src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/common/MemberDto.java
src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/common/MessageDto.java
src/main/java/com/ktb/cafeboo/domain/coffeechat/service/ChatService.java
src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatMessageService.java
src/main/java/com/ktb/cafeboo/global/config/SecurityConfig.java
src/main/java/com/ktb/cafeboo/global/infra/redis/stream/listener/RedisStreamListener.java

- 메시징 관련 부분에서 있었던 데이터 필드명 차이 수정 진행
- domain 변경에 따라 CORS 예외 항목에 새 domain name 추가
- 읽고 이해 안되는 부분 있으시면 코멘트 남겨주세요
- 로컬 환경에서 FE 연동을 통한 테스트

[FIX] FE 연동 간 발생한 문제 수정

---

src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/ChatController.java

- MessageExceptionHandler를 도입했으니 message 전송 오류가 생기면 exception을 던지도록 수정
- X
- FE 연동 후 확인 예정

[FIX] 메시지 오류 발생 간 메시지 처리하지 않는 문제 수정

---

Dockerfile
src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatReviewService.java

- LocalDateTime.now().plusHours(9) 적용하여 UTC 환경에서도 KST 기준 시간으로 판단
- 주요 코드 변경 사항 요약
- 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요.
- 직접 테스트한 방법/결과 적기

[FIX] 커피챗 리뷰 작성 요청 시 작성 가능 여부 판단 시각 수정

---

src/main/java/com/ktb/cafeboo/domain/ai/service/CaffeineRecommendationService.java
src/main/java/com/ktb/cafeboo/global/infra/ai/dto/PredictCaffeineLimitByRuleRequest.java

- `PredictCaffeineLimitByRuleRequest` 수정
- x

[FIX] 카페인 권장량 추천 인공지능 호출 DTO수정

---

src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/ErrorStatus.java

- `ErrorStatus`에 `S3_PROFILE_IMAGE_UPLOAD_FAILED` 추가

[FIX] 프로필 이미지 업로드 실패 오류 Enum 추가

---

src/main/java/com/ktb/cafeboo/domain/ai/controller/DrinkRecommendationController.java
src/main/java/com/ktb/cafeboo/domain/ai/service/DrinkRecommendationService.java

AI 음료 추천 API 테스트를 위한 로그 추가
- 컨트롤러, 서비스 시작 - 종료 간 흐름을 파악하기 위한 로깅 추가
- X
- 개발 서버에서 확인 예정

[FEAET] 로깅 추가
