- src/main/java/com/ktb/cafeboo/domain/user/model/UserFavoriteDrinks.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/ApiResponse.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/BaseCode.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/SuccessStatus.java
- API 응답의 일관성을 위해 ApiResponse<T> 클래스 작성
- onSuccess: 기본 성공 응답 생성 (SuccessStatus.OK 기반)
- of: 상황별 BaseCode 기반 커스텀 성공 응답 생성
- onFailure: 에러 코드 기반 실패 응답 처리
- data 필드는 null일 경우 JSON 응답에서 제외되도록 설정
- 대면으로 리뷰 진행완료
> API 응답 포멧 통일

- src/main/java/com/ktb/cafeboo/domain/caffeinediary/controller/CaffeineIntakeController.java
- src/main/java/com/ktb/cafeboo/domain/caffeinediary/model/CaffeineResidual.java
- src/main/java/com/ktb/cafeboo/domain/caffeinediary/repository/CaffeineResidualRepository.java
- src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineIntakeService.java
- src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineResidualService.java
- src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/ResidualAmountService.java
- src/main/java/com/ktb/cafeboo/domain/drink/model/Cafe.java
- src/main/java/com/ktb/cafeboo/domain/drink/model/Drink.java
- src/main/java/com/ktb/cafeboo/domain/report/controller/DailyReportController.java
- src/main/java/com/ktb/cafeboo/domain/report/controller/WeeklyReportController.java
- src/main/java/com/ktb/cafeboo/domain/report/dto/DailyCaffeineReportResponse.java
- src/main/java/com/ktb/cafeboo/domain/report/dto/WeeklyCaffeineReportResponse.java
- src/main/java/com/ktb/cafeboo/domain/report/model/DailyStatistics.java
- src/main/java/com/ktb/cafeboo/domain/report/model/WeeklyReport.java
- src/main/java/com/ktb/cafeboo/domain/report/repository/DailyStatisticsRepository.java
- src/main/java/com/ktb/cafeboo/domain/report/repository/WeeklyReportRepository.java
- src/main/java/com/ktb/cafeboo/domain/report/service/DailyReportService.java
- src/main/java/com/ktb/cafeboo/domain/report/service/DailyStatisticsService.java
- src/main/java/com/ktb/cafeboo/domain/report/service/WeeklyReportService.java
- https://github.com/100-hours-a-week/13-Cafeboo-BE/pull/16
- DailyStatistics Service에서 잔존량과 관련된 부분을 담당하는 Caffeine Residual Service를 분리했습니다.
- /api/v1/reports/daily, /api/v1/reports/weekly API을 담당하는 Controller 부분을 구현했습니다. 
- Drink 엔티티, CaffeineIntakeController 서비스 기획에 맞게 리팩토링 진행.
- 각 기능 별로 흐름 위주로 체크 해주세요.
- API Response의 경우 작업하던 branch에 대면을 통해 정했던 양식이 반영되어 있지 않은 상태라 merge 진행 후 새로운 branch 파서 수정 진행하겠습니다. 
- Postman을 활용한 수동 API 호출 및 결과 체크 진행
> ✨ feat : 일일, 주간 리포트 기능 구현

- src/main/java/com/ktb/cafeboo/domain/auth/controller/AuthController.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/ApiResponse.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/exception/ApiExceptionHandler.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/exception/CustomApiException.java
- 컨트롤러, 서비스 등 비즈니스 로직 상에서 에서 try-catch 없이 예외만 던지면 일관된 JSON 구조로 예외 응답 반환
- 예외응답 관리를 위한 exception handler 추가하였습니다.
- 예시로 AuthController에서 지원하지 않는 소셜 타입 오류를 반환하는 부분 참고하시면 좋을 것 같습니다.
- postman으로 정상 예외 응답 생성 확인
> CustomApiException 및 ApiExceptionHandler 구현을 통한 예외 응답 통일

- src/main/java/com/ktb/cafeboo/domain/auth/controller/AuthController.java
- src/main/java/com/ktb/cafeboo/domain/auth/service/AuthService.java
- src/main/java/com/ktb/cafeboo/global/security/JwtAuthenticationFilter.java
- src/main/java/com/ktb/cafeboo/global/security/userdetails/CustomUserDetails.java
- 로그아웃 등 accessToken 기반 인증 API에서 Authorization 헤더 직접 파싱 대신 Spring Security의 @AuthenticationPrincipal 기반 CustomUserDetails 사용
- 인증된 사용자 ID를 안전하게 접근하도록 서비스 로직 개선
- AuthController에 로그아웃 api 에서 유저 인증 정보 조회해오는 로직 확인해주세요!
> ♻️refactor: 인증된 사용자 정보 추출 시 @AuthenticationPrincipal 적용

- src/main/java/com/ktb/cafeboo/domain/user/controller/UserController.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserCaffeineInfoCreateRequest.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserCaffeineInfoCreateResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserCaffeineInfoResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserCaffeineInfoUpdateRequest.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserCaffeineInfoUpdateResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserHealthInfoCreateRequest.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserHealthInfoCreateResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserHealthInfoResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserHealthInfoUpdateRequest.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserHealthInfoUpdateResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserProfileResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/mapper/UserCaffeineInfoMapper.java
- src/main/java/com/ktb/cafeboo/domain/user/mapper/UserHealthInfoMapper.java
- src/main/java/com/ktb/cafeboo/domain/user/model/UserAlarmSetting.java
- src/main/java/com/ktb/cafeboo/domain/user/model/UserCaffeinInfo.java
- src/main/java/com/ktb/cafeboo/domain/user/model/UserHealthInfo.java
- src/main/java/com/ktb/cafeboo/domain/user/repository/UserCaffeineInfoRepository.java
- src/main/java/com/ktb/cafeboo/domain/user/repository/UserHealthInfoRepository.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserCaffeineInfoService.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserHealthInfoService.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserService.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/SuccessStatus.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/exception/ApiExceptionHandler.java
- src/main/java/com/ktb/cafeboo/global/config/SecurityConfig.java
- src/main/java/com/ktb/cafeboo/global/security/JwtAuthenticationFilter.java
- src/main/java/com/ktb/cafeboo/global/util/AuthChecker.java
- src/main/resources/application.properties
- UserCaffeineInfoController, UserCaffeineInfoService 추가
- UserCaffeineInfoMapper에 toEntity, updateEntity, toResponse 메서드 구현
- 카페인 정보 관련 요청/응답 DTO 5종 정의 및 적용
- 응답 상태 코드 Enum 추가
- Dto 매핑 로직에 집중해서 검토해주세요
- Postmane 으로 /api/v1/users/{userId}/caffeine 경로에 대해 POST, PATCH, GET 메서드 요청 수행
- 주요 응답(카페인 정보 중복 생성 시 409, 본인 외 유저 ID 접근 시 403, 카페인 정보 미등록 시 404) 확인 완료
> ✨ feat: 유저 카페인 프로필 CRU API 개발

- src/main/java/com/ktb/cafeboo/domain/auth/service/AuthService.java
- src/main/java/com/ktb/cafeboo/global/security/JwtAuthenticationFilter.java
- src/main/java/com/ktb/cafeboo/global/security/JwtProvider.java
- Refresh 토큰 생성 시 subject를 userId가 아닌 email로 잘못 설정한 문제 수정
- JwtProvider에서 subject가 null일 경우 예외 처리 로직 추가
- JwtProvider에서 Long.parseLong 수행 전 null 및 형식 검증 로직 추가
- 사용자 인증 실패 시 ACCESS_TOKEN_INVALID 예외를 안전하게 반환하도록 개선
- Postman을 사용하여 재발급 받은 토큰이 정상적으로 인증되는 것을 테스트하였습니다.
> 🐛fix: JWT subject 누락 및 파싱 예외 대응 로직 추가

- src/main/java/com/ktb/cafeboo/domain/user/controller/UserController.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserAlarmSettingCreateRequest.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserAlarmSettingCreateResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserAlarmSettingResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserAlarmSettingUpdateRequest.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserAlarmSettingUpdateResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/mapper/UserAlarmSettingMapper.java
- src/main/java/com/ktb/cafeboo/domain/user/model/UserAlarmSetting.java
- src/main/java/com/ktb/cafeboo/domain/user/model/UserCaffeinInfo.java
- src/main/java/com/ktb/cafeboo/domain/user/repository/UserAlarmSettingRepository.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserAlarmSettingService.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserCaffeineInfoService.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/SuccessStatus.java
- UserAlarmSettingController, UserAlarmSettingService, UserAlarmSettingRepository 추가
- UserAlarmSettingMapper에 toEntity, updateEntity, toResponse 메서드 구현
- 알림설정 정보 관련 요청/응답 DTO 5종 정의 및 적용
- 응답 상태 코드 Enum 추가
- Dto 구성에 관해 고민사항이 있습니다. 추후 리팩토링 사항으로 고려 중입니다
- Postmane 으로 /api/v1/users/{userId}/alarm 경로에 대해 POST, PATCH, GET 메서드 요청 수행
- 주요 응답(알림설정 정보 중복 생성 시 409, 본인 외 유저 ID 접근 시 403, 알림설정 정보 미등록 시 404) 확인 완료
> ✨feat: 유저 알림설정 정보 생성, 조회, 수정 기능 구현

- src/main/java/com/ktb/cafeboo/domain/auth/dto/KakaoLoginResponse.java
- src/main/java/com/ktb/cafeboo/domain/auth/service/KakaoOauthService.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserService.java
- KakaoLoginResponse dto 필드명 수정
- KakaoOauthService login 메서드 내 온보딩 완료 상태 판단 로직 수정
- UserService 내 온보딩 상태 검증 메서드 추가
- 온보딩 데이터 유무에 따른 requiresOnboarding 필드 정상 반환 확인
> 🐛fix: 카카오 로그인 응답의 온보딩 여부 판단 로직 수정

- src/main/java/com/ktb/cafeboo/domain/user/controller/UserController.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserService.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/ErrorStatus.java
- UserService에 getUserProfile 메서드 추가
- UserController에 GET /api/v1/users/{userId}/profile 엔드포인트 추가
- 추후 challengeCount 계산 로직을 실제 챌린지 기능과 연동할 예정인데, 해당 위치나 설계 방식에 대한 피드백 좋습니다
- Postman 테스트
> 유저 기본 프로필 조회 API 구현

- src/main/java/com/ktb/cafeboo/domain/auth/dto/KakaoLoginResponse.java
- src/main/java/com/ktb/cafeboo/domain/auth/dto/TokenRefreshResponse.java
- src/main/java/com/ktb/cafeboo/domain/auth/service/AuthService.java
- src/main/java/com/ktb/cafeboo/domain/auth/service/KakaoOauthService.java
- src/main/java/com/ktb/cafeboo/domain/recommend/service/CaffeineRecommendationService.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserAlarmSettingCreateResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserAlarmSettingUpdateResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserCaffeineInfoCreateResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserCaffeineInfoUpdateResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserHealthInfoCreateResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserHealthInfoUpdateResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/mapper/UserCaffeineInfoMapper.java
- src/main/java/com/ktb/cafeboo/domain/user/model/UserFavoriteDrinkType.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserAlarmSettingService.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserCaffeineInfoService.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserHealthInfoService.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/client/AiServerClient.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/dto/PredictCaffeineLimitByRuleRequest.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/dto/PredictCaffeineLimitByRuleResponse.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/dto/PredictCaffeineLimitRequest.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/dto/PredictCaffeineLimitResponse.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/dto/PredictCanIntakeCaffeineRequest.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/dto/PredictCanIntakeCaffeineResponse.java
- CaffeineRecommendationService 신규 생성
- UserCaffeineInfoService, UserHealthInfoService 내 AI 서버 호출 로직 추가
- AI 서버 요청/응답 DTO 및 예외 처리 보완
- 기존 userId 타입 일관화를 위한 DTO 필드 수정(Long → String)
- 서비스 레이어에서의 예측 실패 fallback 로직이 적절한지 검토 부탁드립니다.
- 현재 인공지능 서버 배포 전이라 통신 테스트는 수행하지 못하였습니다
> ✨feat: AI 서버 연동을 통한 최대 카페인 허용량 예측 기능 구현

- .gitignore
- src/main/java/com/ktb/cafeboo/domain/caffeinediary/controller/CaffeineIntakeController.java
- src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineIntakeService.java
- src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineResidualService.java
- src/main/java/com/ktb/cafeboo/domain/report/controller/WeeklyReportController.java
- src/main/java/com/ktb/cafeboo/domain/report/dto/CoffeeTimeStats.java
- src/main/java/com/ktb/cafeboo/domain/report/dto/ReportDTO.java
- src/main/java/com/ktb/cafeboo/domain/report/model/DailyStatistics.java
- src/main/java/com/ktb/cafeboo/domain/report/repository/DailyStatisticsRepository.java
- src/main/java/com/ktb/cafeboo/domain/report/service/DailyReportService.java
- src/main/java/com/ktb/cafeboo/domain/report/service/DailyStatisticsService.java
- src/main/java/com/ktb/cafeboo/domain/report/service/WeeklyReportService.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/client/AiServerClient.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/dto/CreateWeeklyReportRequest.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/dto/CreateWeeklyReportResponse.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/dto/PredictCanIntakeCaffeineRequest.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/dto/PredictCanIntakeCaffeineResponse.java
- AI 백엔드와의 연결을 통한 카페인 추가 섭취 여부를 판단하기 위해 AI 엔드포인트로 요청을 보내는 부분 구현
- DTO 관련해 AI 백엔드에서 BE에서 보낸 데이터를 인식하지 못함에 따른 @JsonProperty 추가
- 컨트롤러 - 서비스의 역할을 명확히 하기 위한 일부 코드 리팩토링
- DTO 관련 JsonProperty 부분, 그 외 주간 섭취 내역에 대한 메시지 생성을 batch로 처리함에 따른 schedule 관련 내용 생각하시는 부분 있으면 알려주세요.
- AI 백엔드 서버를 띄운 상태로 상태 코드 및 응답 결과 확인
> ✨Feat: AI의 rule 기반 판단에 따른 메시지의 생성 및 저장 기능 추가

- src/main/java/com/ktb/cafeboo/domain/report/controller/DailyReportController.java
- src/main/java/com/ktb/cafeboo/domain/report/controller/WeeklyReportController.java
- src/main/java/com/ktb/cafeboo/domain/report/model/MonthlyReport.java
- src/main/java/com/ktb/cafeboo/domain/report/model/WeeklyReport.java
- src/main/java/com/ktb/cafeboo/domain/report/service/DailyStatisticsService.java
- src/main/java/com/ktb/cafeboo/domain/report/service/MonthlyReportService.java
- src/main/java/com/ktb/cafeboo/domain/report/service/WeeklyReportScheduler.java
- src/main/java/com/ktb/cafeboo/domain/report/service/WeeklyReportService.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/client/AiServerClient.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/dto/CreateWeeklyReportRequest.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/dto/CreateWeeklyReportResponse.java
- 스케줄링을 통해 비동기 요청 보내는 스케줄러 서비스 구현
- DailyStatisticsService에서 데이터 관리 동작 순서 수정
- Report 도메인의 WeeklyReportScheduler 한 번 봐주세요
- WeeklyReport 도메인에 WeeklyReportScheduler의 메서드 호출을 위한 테스트용 API를 작성했습니다. 테스트 후 문제가 없다면 삭제하겠습니다.
- postman, dataGrip을 활용한 수동 체크
> ✨Feat: AI 배치 전략에 맞춰 스케줄링을 통해 비동기 요청 보내는 기능

- src/main/java/com/ktb/cafeboo/domain/recommend/service/CaffeineRecommendationService.java
- CaffeineRecommendationService 내 getPredictedCaffeineLimitByRule 메서드 수정
- 요청 바디 빌드하는 부분 수정
> fix: 카페인 허용량 예측 api 요청 dto 변경에 따른 서비스 로직 수정

- src/main/java/com/ktb/cafeboo/domain/drink/service/DrinkService.java
- src/main/java/com/ktb/cafeboo/domain/report/service/DailyStatisticsService.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/ErrorStatus.java
디버깅용 에러 추가: 기존에는 음료 정보, 음료 사이즈별 정보가 없을 때 모두 DRINK_NOT_FOUND를 return. 음료 정보, 음료 사이즈 중 어떤게 문제가 되는지 확인하기 위해 DRINK_SIZE_NOT_FOUND 에러 추가.
FE에서 봤을 때 권장량의 n% 섭취 중 문구에서 소수점 5자리까지 나오는 것으로 확인. (int) 캐스팅을 통해 정수형으로 직관적으로 보일 수 있도록 수정
- 디버깅용 ErrorStatus DRINK_SIZE_NOT_FOUND 추가
- x
> ✏️Chore: 음료 등록 관련 수정

- src/main/java/com/ktb/cafeboo/domain/user/model/User.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserService.java
- UserService내 logout 메서드 수정
- User 엔티티 withdraw 메서드 삭제
- postman과 로컬 데이터베이스로 회원탈퇴 검증
> 🐛fix: 회원탈퇴 비즈니스 로직 수정 및 리팩토링

- src/main/java/com/ktb/cafeboo/domain/report/service/DailyReportService.java
- src/main/java/com/ktb/cafeboo/domain/report/service/DailyStatisticsService.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserCaffeineInfoService.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserHealthInfoService.java
- UserCaffeineInfoService에서 카페인 관련 수치 변동 발생 시, 일일 통계 부분의 AI 메시지에도 바뀐 카페인 관련 수치를 바탕으로 메시지를 생성해 반영하도록 수정 진행했습니다. 
- UserCaffeineInfoService 변경 내역 한 번 확인해주세요.
> 🐛Fix: 유저 마이페이지에서 정보 수정 시 카페인 한계치 값 변경됨에 따른 일일 통계 AI 메시지 내용 수정

- src/main/java/com/ktb/cafeboo/domain/caffeinediary/service/CaffeineResidualService.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserHealthInfoService.java
섭취 내역 삭제/수정 시 카페인 잔존량 관련 계산 로직 변경
- 섭취 내역 삭제/수정 시 카페인 잔존량 관련 계산 로직 변경
- X
- 반영 후 배포 환경에서 DataGrip을 활용해 수동 테스트 할 예정
> 🐛Fix: 섭취 내역 삭제/수정 시 카페인 잔존량 관련 계산 로직 변경

- src/main/java/com/ktb/cafeboo/domain/auth/controller/AuthController.java
- src/main/java/com/ktb/cafeboo/domain/auth/model/OauthToken.java
- src/main/java/com/ktb/cafeboo/domain/auth/repository/OauthTokenRepository.java
- src/main/java/com/ktb/cafeboo/domain/auth/service/KakaoOauthService.java
- src/main/java/com/ktb/cafeboo/domain/user/controller/UserController.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserService.java
- src/main/java/com/ktb/cafeboo/global/infra/kakao/client/KakaoUserClient.java
- src/main/java/com/ktb/cafeboo/global/security/JwtProvider.java
- `UserService`, `AuthController`, `KakaoOauthService` 등 주요 서비스/컨트롤러 로직 변경
- `OauthToken` 엔티티, 레포지토리 추가
- `KakaoUserClient` 를 통한 unlink 호출 메서드 추가
- unlinkKakao() 예외 처리를 현재는 단순 호출 후 삭제하는 구조인데, 실패 시 어떻게 처리할지에 대한 의견도 주시면 감사하겠습니다
- Postman을 통해 로그인 → 로그아웃 → 회원 탈퇴 전체 흐름 테스트
- 쿠키 삭제 여부 확인 (Set-Cookie: refreshToken=; Max-Age=0)
- 카카오 계정 연동 해제 여부 확인 (https://developers.kakao.com/console/app → 사용자 목록)
Fixes #59
> ✨feat: 소셜 로그인 연동 상태 저장 및 연결 해제 기능 구현

- src/main/java/com/ktb/cafeboo/domain/auth/controller/AuthController.java
- src/main/java/com/ktb/cafeboo/domain/auth/service/KakaoOauthService.java
- src/main/java/com/ktb/cafeboo/global/infra/kakao/client/KakaoUserClient.java
- 카카오 인증 서버에 로그아웃 요청하는 메서드 추가
- 컨트롤러에서 응답 방식 수정
- 기존: 303 See Other 응답 + Location 헤더로 로그아웃 URL 전달
- 변경: 204 No Content 응답으로 자체 로그아웃 처리 완료만 전달
- 찾아보면서 인증 로직을 조금 더 깊이 설계해야하는 지점을 발견하였습니다
(카카오 인증 서버 토큰의 재발급 등)
- 우선은 배포를 위해 오류가 나지 않도록 설정해두었고, 고도화는 따로 진행하겠습니다.
- Postman으로 정상 반환
Fixes #78
> Fix: 로그아웃 요청시, 리다이렉션 응답으로 인한 CORS오류 수정

- src/main/java/com/ktb/cafeboo/global/security/JwtAuthenticationFilter.java
- JwtAuthenticationFilter 내에서 토큰 유효성 검사 실패 시 CustomApiException을 catch
- 인증 실패 시 SecurityContextHolder 초기화 및 직접 JSON 응답 작성
- 인증 실패 후 filterChain.doFilter() 호출 방지하여 불필요한 필터 흐름 차단
- CustomApiException을 catch한 뒤 다음 처리 수행:
- SecurityContextHolder.clearContext() 호출로 인증 정보 초기화
- response.setStatus(HttpServletResponse.SC_UNAUTHORIZED)로 401 반환
- response.getWriter().write(...)로 code, message 포함한 JSON 응답 작성
- 인증 성공한 경우에만 filterChain.doFilter() 호출되도록 분기 구조 정리
- Postman으로 테스트
> Fix: JWT 인증 실패 시 응답 바디 포함한 401 반환 및 필터 체인 중단

- src/main/java/com/ktb/cafeboo/global/config/SecurityConfig.java
AI 주간 리포트 생성 기능을 테스트 하는 과정에서 AI 서버로 요청을 보내고 받는 것 까지는 제대로 동작하는 것을 확인했습니다.
하지만 AI 서버에서 비동기로 리포트 생성 완료 후 콜백을 통해 BE의 엔드포인트 호출 시 403 Forbidden 에러가 발생합니다.
해당 부분을 방지하기 위해 SecurityConfig에서 AI 콜백 부분에 대해서 Authorization이 요구되지 않도록 수정 진행합니다.
- AI 서버에서 비동기 리포트 생성 완료 후 호출하게 되는 BE 엔드포인트의 Authorization 헤더 필수 여부를 수정했습니다.
- X
> 🐛Fix: AI 콜백 호출에 대한 403 오류 수정

- build.gradle
- src/main/java/com/ktb/cafeboo/domain/auth/service/KakaoOauthService.java
- src/main/java/com/ktb/cafeboo/domain/user/model/User.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/ktb/cafeboo/global/config/S3Config.java
- src/main/java/com/ktb/cafeboo/global/infra/s3/S3Properties.java
- src/main/java/com/ktb/cafeboo/global/infra/s3/S3Uploader.java
- src/main/resources/application.properties
- `S3Uploader`: AWS S3 이미지 업로드 공통 클래스 구현
- `KakaoOauthService`: 내부에서 카카오 프로필 이미지 업로드 및 저장 로직 추가
- 회원가입 시, 이미지 새로 저장
- 기존 회원은 이미지 URL이 null인 경우만 업데이트되도록 조건 분기
- S3 upload 공통 메서드 사용에 대해 궁금한 사항이 있으면 말씀해주세요
- AWS 이미지 폴더 구성
**cafeboo/**
├── **defaults/**
│   └── default-profile.png
├── **profile-uploads/**
└── **review-uploads/**
fixes: #135
> [FEAT] 카카오 프로필 이미지 연동 및 S3 업로드 기능 개발

- build.gradle
- src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/ChatController.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/CoffeeChatController.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/model/CoffeeChatMessage.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/model/CoffeechatMessage.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/ChatService.java
- src/main/java/com/ktb/cafeboo/global/config/SecurityConfig.java
- 채팅방 별로 Redis Stream의 listener 설정
Redis Stream의 경우 consumer group (listener) 단위로 작업을 나눠서 처리하도록 할 수 있음. 이 때, 각 채팅방에 여러 consumer group이 할당되는 경우, 동일한 메시지를 여러 번 처리하게 되므로 비효율적임.
이러한 부분을 방지하기 위해 각 채팅방 별로 하나의 listener만 설정되도록 구현을 진행.
- isUserJoinedRoom() 메서드 추가
채팅방에 입장하는 경우는 두 가지 대표 케이스가 존재.
i. 신규 가입
ii. 이미 가입한 사람이 재입장
이 때, 각 유저는 입장을 하며 해당 채팅방에 대해 subscribe를 진행하게 되는데 이미 가입한 사람이 재입장하는 경우에는 이 과정이 불필요함.
따라서, 신규 가입인지 재입장인지를 판별하기 위해 해당 메서드를 추가.
- NOACK 상태의 메시지를 처리하는 스케쥴러 및 pendingMessageProcessor 추가
네트워크 오류, 서버 오류 등이 발생 시 Redis Stream에는 메시지가 전달되었지만 ACK되지 않을 가능성이 존재함. NOACK 상태의 메시지는 자원을 불필요하게 차지하는 상태이므로 이를 해소시킬 수 있는 로직이 필요.
따라서, 일정 주기로 NOACK (= PENDING) 상태의 메시지를 처리하는 PendingMessageProcessor를 스케쥴러를 통해 실행하도록 하는 기능을 추가.
- 현재 채팅방과 같은 데이터의 경우 DB 상에 저장하는 부분이 미구현 상태입니다. 채팅의 경우 서버가 실행되는 동안에는 Redis 상에 저장되는 것을 …
> FEAT: 채팅 기능 추가

- src/main/java/com/ktb/cafeboo/domain/auth/service/TokenBlacklistService.java
- src/main/java/com/ktb/cafeboo/global/config/SecurityConfig.java
- src/main/java/com/ktb/cafeboo/global/security/JwtAuthenticationFilter.java
- src/main/java/com/ktb/cafeboo/global/security/JwtProvider.java
- JwtAuthenticationFilter에서 /auth/refresh 요청에 대해 accessToken 만료는 허용, 블랙리스트만 검사
- TokenBlacklistService에 만료된 토큰을 처리할 수 있는 decodeExpiredToken() 기반 블랙리스트 등록 로직 분리 (addToBlacklist(String accessToken))
- x
- postman 활용
fixes: #150
> [FIX]: 토큰 재발급 오류 수정

- src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/ChatController.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/CoffeeChatListResponse.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/StompMessage.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/StompMessagePublish.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/ChatService.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatMessageService.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatService.java
- src/main/java/com/ktb/cafeboo/global/config/RedisConfig.java
- src/main/java/com/ktb/cafeboo/global/infra/redis/stream/listener/RedisStreamListener.java
- StreamMessageListenerContainer
StreamMessageListenerContainer에서 사용되는 데이터가 <String, ?> 에서 <String, MapRecord<String, String, String>>의 형태로 변환됨에 따라 해당 자료구조를 사용하는 부분의 코드를 전반적으로 수정했습니다. 
- DTO 추가
기존 구현에 사용했던 CoffeeChatMessage DTO의 경우 STOMP를 통해 전송하는 채팅의 payload에 담긴 내용보다 많은 정보를 필요로 했습니다. 그렇기에 실제 payload와 DTO 매핑 과정에서 오류가 발생했고, chatService.handleNewMessage()가 호출되더라도 전송된 메시지가 Redis Stream에 publish 되지 않는 문제가 발생했습니다. 
이에, 새로운 STOMP에서 전송되는 메시지에 사용할 StompMessage DTO를 선언해 사용하는 방식으로 수정 진행했습니다. 
Redis Stream에 메시지를 publish 하는 과정에서 StompMessage DTO에서 API 명세에 맞춰 형식을 변환할 필요가 있었습니다. 이에 API 명세에 대응되는 StompMessagePublish DTO를 선언해 전송된 채팅 메시지를 가공하여 Redis Stream에 publish 될 수 있도록 수정 진행했습니다. 
- 채팅 저장 기능 구현
기존에는 Redis에만 채팅 기록이 저장되었고 서버 재부팅, Redis 및 네트워크 오류 발생 시 데이터 손실로 이어질 수 있었습니다. 이에 채팅 전송 간, 프로젝트에서 사용하는 MySQL에 저장된 …
> [REFACTOR] 채팅 기능 테스트 간 발생한 오류 수정

- src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/CoffeeChatController.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/CoffeeChatReviewController.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/CoffeeChatCreateResponse.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/CoffeeChatDetailResponse.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/CoffeeChatListResponse.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/CoffeeChatMessagesResponse.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/CoffeeChatReviewLikeResponse.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/model/CoffeeChatLike.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/repository/CoffeeChatLikeRepository.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatLikeService.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/SuccessStatus.java
- src/main/java/com/ktb/cafeboo/global/enums/CoffeeChatLikeStatus.java
- `CoffeeChatLike` 엔티티 및 Repository 추가
- `CoffeeChatLikeService` 생성 및 toggleLike 로직 구현
- `CoffeeChatReviewController`에 좋아요/취소 API 엔드포인트 추가
- `CoffeeChat` 엔티티에 `likesCount` 필드 및 증감 메서드 추가
- 좋아요 기능은 **유저 인증 정보(@AuthenticationPrincipal)**를 기반으로 동작하며,
그 외의 유효성 검증은 따로 두지 않았습니다.
- 해당 API는 토글 형태로 동작하기 때문에, 중복 좋아요나 중복 취소 요청에 대한 별도 예외 처리 없이 상태만 반전하도록 구현되었습니다.
- 혹시 생각나는 예외 상황이 있다면 코멘트 남겨주세요
- 좋아요 생성 요청
- 좋아요 취소 요청
> [FEAT] 커피챗 후기 좋아요/취소 기능 구현 

- src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/CoffeeChatController.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/CoffeeChatMembershipCheckResponse.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatMemberService.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/SuccessStatus.java
- AccessToken의 `userId`기반 조회
- 커피챗 참여 여부 조회 API의 컨트롤러, 서비스 메서드 추가 및 dto 클래스 작성
- x
Postman
- 참여 O 
- 참여 X
Fixes: #140
> [FEAT] 커피챗 참여 여부 조회 API 구현

- src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/CoffeeChatController.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/CoffeeChatReviewController.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/CoffeeChatListResponse.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/ChatService.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatMemberService.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatService.java
- 비즈니스 로직 분리
CoffeeChatService에서 현재 create() 메서드에서 join() 메서드에서 진행되어야 할 가입 동작이 같이 진행되어 프로그램 실행 간 흐름에서 꼬이는 문제가 존재했습니다.
create() 메서드에서 커피챗 생성 후 coffee chat member list의 갱신을 진행하던 것에서 생성 이후 join() 메서드가 호출되며 가입 및 중복 가입 조건을 체크하는 방식으로 구현을 수정했습니다.
- 데이터 타입 수정
FE 수정이 번거로움에 따라 FE에서 보내는 데이터 타입인 String에 대응되도록 BE의 @PatthVariable을 String 타입으로 변경했습니다.
- 오류 수정
i. 전체 커피챗 조회 간 발생하던 문제 
기존 구현의 경우 커피챗을 탐색하며 가져온 list에 대해 writer 정보가 없다면 Custom Api Exception을 던지도록 했고 이 과정에서 FE에서 본래 나와야 할 "커피챗 목록이 존재하지 않습니다" 라는 디폴트 메시지 대신 "조회 간 오류가 발생했습니다"라는 에러 메시지가 출력되었습니다.
이를 방지하기 위해 WriterDTO 구성 간 Optional이 비어있는 경우 임의로 default MemberDto를 생성해 return하도록 수정했습니다.
ii. 잘못된 정보를 반환하던 문제
.memberId(String.valueOf(memberOpt.get().getId())) 의 경우 DB 상 저장되어 있는 CoffeeChatMember의 unique id를 반환하도록 하는 것이고 이는 실제 유저의 id 값에 해당하는 값이 아닙니다.
해당 정보가 …
> [REFACTOR] FE 연동 간 발생한 문제 수정 - deploy test

- src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/CoffeeChatController.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/CoffeeChatReviewController.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/CoffeeChatListResponse.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/ChatService.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatMemberService.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatService.java
- 비즈니스 로직 분리
CoffeeChatService에서 현재 create() 메서드에서 join() 메서드에서 진행되어야 할 가입 동작이 같이 진행되어 프로그램 실행 간 흐름에서 꼬이는 문제가 존재했습니다.
create() 메서드에서 커피챗 생성 후 coffee chat member list의 갱신을 진행하던 것에서 생성 이후 join() 메서드가 호출되며 가입 및 중복 가입 조건을 체크하는 방식으로 구현을 수정했습니다.
- 데이터 타입 수정
FE 수정이 번거로움에 따라 FE에서 보내는 데이터 타입인 String에 대응되도록 BE의 @PatthVariable을 String 타입으로 변경했습니다.
- 오류 수정
i. 전체 커피챗 조회 간 발생하던 문제 
기존 구현의 경우 커피챗을 탐색하며 가져온 list에 대해 writer 정보가 없다면 Custom Api Exception을 던지도록 했고 이 과정에서 FE에서 본래 나와야 할 "커피챗 목록이 존재하지 않습니다" 라는 디폴트 메시지 대신 "조회 간 오류가 발생했습니다"라는 에러 메시지가 출력되었습니다.
이를 방지하기 위해 WriterDTO 구성 간 Optional이 비어있는 경우 임의로 default MemberDto를 생성해 return하도록 수정했습니다.
ii. 잘못된 정보를 반환하던 문제
.memberId(String.valueOf(memberOpt.get().getId())) 의 경우 DB 상 저장되어 있는 CoffeeChatMember의 unique id를 반환하도록 하는 것이고 이는 실제 유저의 id 값에 해당하는 값이 아닙니다.
해당 정보가 …
> [REFACTOR] FE 연동 간 발생한 문제 수정

- src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/CoffeeChatController.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/CoffeeChatMembershipCheckResponse.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/StompMessagePublish.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/repository/CoffeeChatMemberRepository.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/ChatService.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatMemberService.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatService.java
- memberId를 기준으로 방장으로 설정하고 있기 때문에 이전에 삭제했던 memberid에 대한 부분을 DTO에 추가 반영
커피챗 생성, 가입 기준으로 host 정보가 true/false로 설정되어야 하는데 이전 구현에서는 join() 메서드에서 멤버가 추가됨에 따라 무조건적으로 isHost 필드가 false로 설정되었음. 이에 createCoffeeChat()에서 호출되는지 joinCoffeeChat() 에서 호출되는지 판단하기 위한 Boolean 파라미터 isHost 를 추가했습니다.
- 코멘트 남겨주세요
- FE 연동을 통한 로컬 환경에서 테스트 진행
> [FIX] 커피챗 관련 오류 수정

- docs/text-censorship-filter-guide.md  
- src/main/java/com/ktb/cafeboo/global/censorship/CensorshipStrategy.java
- src/main/java/com/ktb/cafeboo/global/censorship/TextCensorshipFilter.java
- src/main/java/com/ktb/cafeboo/global/censorship/filters/AiCensorshipFilter.java
- src/main/java/com/ktb/cafeboo/global/censorship/filters/TrieCensorshipFilter.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/client/AiServerClient.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/dto/ToxicityDetectionRequest.java
- src/main/java/com/ktb/cafeboo/global/infra/ai/dto/ToxicityDetectionResponse.java
- src/main/java/com/ktb/cafeboo/global/infra/s3/S3Downloader.java
- src/main/resources/application-dev.properties
- src/main/resources/application-prod.properties
- src/main/resources/application.properties
- `CensorshipStrategy` enum 추가
- `TrieCensorshipFilter` 구현 및 S3 키워드 로딩 적용
- `AiCensorshipFilter` 구현 (AI 서버 연동)
- 현재 기능 구현을 해두었고 각 서비스에 호출해서 사용하면 됩니다.
- `docs/text-censorship-filter-guide.md` 경로에 사용 메뉴얼을 첨부해두었습니다. 
읽어 보시고, 사용법이 헷갈리다면 말씀주세요. 빠르게 적용하기 위해 검열 적용할 부분을 나누어 맡아서 적용해도 좋을 것 같습니다.
- [메뉴얼 노션으로 보기](https://www.notion.so/TextCensorshipFilter-213b43be904c8056be7ff54159d88c3f)
- 전략을 번갈아 선택해가며 모두 각각의 필터가 정상 수행됨을 확인
closed: #159, #160
> [FEAT] 커피챗 검열 기능 구현

- src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/CoffeeChatReviewController.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/CoffeeChatReviewResponse.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/common/CoffeeChatReviewPreviewDto.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/repository/CoffeeChatLikeRepository.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatLikeService.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatReviewService.java
- 사용자가 해당 커피챗 리뷰에 좋아요를 눌렀는지 여부를 판단하기 위한 liked 필드 도입
- CoffeeChatReviewPreviewDto, CoffeeChatDetailResponse 등 응답 DTO에 liked 포함
- CoffeeChatLikeService.hasLiked(userId, coffeeChatId) 메서드 구현 및 응답 구성 시 활용
- 유저의 좋아요 여부 판단 시, 특정 서비스가 직접 레포지토리에 접근하지 않고 `CoffeeChatLikeService.hasLiked`를 활용한 구조가 적절한지 검토 부탁드립니다.
- 포스트맨
> [FEAT] 커피챗 리뷰 목록 및 상세 응답에 좋아요 여부(liked) 필드 추가

- src/main/java/com/ktb/cafeboo/global/censorship/controller/CensorshipTestController.java
- src/main/java/com/ktb/cafeboo/global/censorship/filters/TrieCensorshipFilter.java
- src/main/java/com/ktb/cafeboo/global/config/SecurityConfig.java
- src/main/resources/application-dev.properties
- src/main/resources/application-prod.properties
- src/main/resources/application.properties
- 화이트리스트 전용 Trie 트리 구조 도입 및 isWhitelisted() 로직 추가
- S3에서 화이트리스트 키워드 파일 별도 로딩 (censorship.whitelist-filename)
-` /internal/censorship/check` API 구현 (GET 방식, 토큰 없이 사용 가능)
-  로컬/개발 환경에서 `GET /internal/censorship/check?text=검열대상` API를 활용하여 트라이 검열을 테스팅할 수 있습니다.
closed: #187
> [FEAT] 검열- 화이트리스트(예외어) 로직 도입

- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/common/MessageDto.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/model/CoffeeChatMessage.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/ChatService.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatMessageService.java
- src/main/java/com/ktb/cafeboo/global/config/WebSocketConfig.java
- 로컬 환경에서 테스트 불가능했던 검열 기능을 활성화했습니다.
- 채팅방 메시지 출력
기획 의도 상 이전 채팅 내역을 조회할 때 Message type이 'TALK', 'ENTER', 'LEAVE' 일 때 다른 방식으로 화면 상에 표시되어야 합니다.
하지만 현재의 API 구현에서는 대화 내역 조회 간 Message type에 대해 구분할 수 있는 필드를 제공하지 않았습니다. 그렇기에 memberId를 기준으로 본인의 메시지라고 판단되면 messag type에 관계 없이 'TALK'에 해당되는 UI로 출력되는 문제가 존재했습니다.
MessageDTO 필드에 MessageType enum 필드를 추가한 것으로 해당 문제를 해결할 수 있을 것이라 기대합니다.
- 채팅방 나가기
채팅방 퇴장 기능 이용 시, 한 번이라도 채팅을 쳤던 이용자는 해당 채팅방에서 탈퇴하는 것이 불가능했습니다.
이는 CoffeeeChatMember와 CoffeeChatMessage가 외래키를 통해 연결되어 발생하는 문제였습니다. CoffeeeChatMember 삭제 시 그와 연관된 CoffeeChatMessage는 CoffeeChatMember 필드에 null을 허용하지 않는 상황이고 이에 따라 외래키 제약 오류를 발생시킵니다.
이에, null을 허용하는 방안으로 수정을 제안합니다.
- 궁금하신 부분 코멘트로 남겨주세요
- 로컬 환경에서 테스트.
> [FIX] 채팅 기능 오류 수정

- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatMessageService.java
- 메시지 조회 시 leaveChat() 메서드 호출 시 퇴장하는 sender가 보낸 메시지는 전부 null로 설정되도록 했습니다.
이 과정에서 컬럼에 null을 포함하는 데이터가 조회되며 500 에러가 발생했고 filtering을 통해 해당 데이터들은 조회되지 않도록 수정했습니다.
- X
- dev 서버에서 로그 분석 및 테스트 진행
> [FIX] FE 연동 간 발생한 필드명 차이 수정

- src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/ChatController.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/ChatService.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/ErrorStatus.java
- 현재 메시지 처리에서 메시지가 검열되는 경우 exception 등이 발생하지 않아 메시지가 보내지지 않았을 때 유저가 어떠한 이유로 보내지지 않았는지 식별하기가 어려운 상황이었습니다.
이에 따라 유저가 메시지 전송 과정에서 발생한 오류를 확인할 수 있도록 exception을 추가해 던지도록 설정했습니다. 
- 테스트 코드 작성 중 에러 처리가 미흡한 부분들에 대한 에러 enum을 추가했습니다. 
- 읽어보신 후 코멘트 남겨주세요.
- 로컬 환경에서 테스트 빌드로 확인
> [FEAT] 검열 시 예외 처리 추가 및 에러 enum 추가

- src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/CoffeeChatController.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatService.java
- src/main/java/com/ktb/cafeboo/domain/user/model/User.java
- `CoffeeChatService#create` 내부에서 호출하던 참여 로직을 `joinMember`로 메서드 분리 및 private으로 변경
- `joinMember`의 인자로 `User` 객체를 넘기도록 수정하여, `userRepository.findById()` 중복 호출 제거
- 테스트 및 유연한 객체 생성을 위한 `User` 객체 `@Builder` 추가
- 테스트 용이성을 위해서 프로덕션 코드를 수정하는 것에 대해서 추후 고민이 필요한 부분인 것 같습니다.
> [REFACTOR] 커피챗 참여 로직 분리 및 User 엔티티 빌더 추가

- src/main/java/com/ktb/cafeboo/domain/auth/service/KakaoOauthService.java
- src/main/java/com/ktb/cafeboo/domain/user/dto/UserProfileResponse.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserService.java
- src/main/java/com/ktb/cafeboo/global/infra/kakao/dto/KakaoUserResponse.java
- `getOrCreateUser` 내부 로직을 `createNewUser`, `updateProfileImage`, `getProfileImageOrDefault` 등으로 분리
- `isDefaultImage` 값에 따라 불필요한 업로드를 방지하고, 공통 기본 프로필 이미지로 fallback 처리
- `UserProfileResponse` DTO에 `profileImageUrl` 필드 추가 및 서비스 로직 연동
-
- 카카오톡 기본 프로필 지정 후, 로그인 진행
- 카카오톡 기본 프로필인 경우, s3 업로드가 진행되지 않고 카테부의 기본 프로필로 저장되는 것 확인
연관이슈
close: #211
> [FEAT] 카카오 기본 프로필 이미지 처리 및 유저 프로필 조회 기능 개선

- src/main/java/com/ktb/cafeboo/domain/coffeechat/dto/StompMessagePublish.java
- StompMessagePublish내 from 메서드 수정
-x
> [FIX] stomp 메세지 유저 프로필 이미지 누락 수정

- src/main/java/com/ktb/cafeboo/domain/coffeechat/scheduler/CoffeeChatScheduler.java
- `@Scheduled(cron = "0 0 9 * * *", zone = "Asia/Seoul")` 으로 변경
-x
> [FIX] 커피챗 만료 스케줄러 실행 시간 변경

- src/main/java/com/ktb/cafeboo/domain/auth/controller/AuthController.java
- src/main/java/com/ktb/cafeboo/domain/auth/dto/GuestLoginResponse.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/CoffeeChatController.java
- src/main/java/com/ktb/cafeboo/domain/coffeechat/controller/CoffeeChatReviewController.java
- src/main/java/com/ktb/cafeboo/domain/user/controller/UserController.java
- src/main/java/com/ktb/cafeboo/domain/user/model/User.java
- src/main/java/com/ktb/cafeboo/domain/user/repository/UserRepository.java
- src/main/java/com/ktb/cafeboo/domain/user/scheduler/GuestCleanupScheduler.java
- src/main/java/com/ktb/cafeboo/domain/user/service/UserService.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/code/status/SuccessStatus.java
- src/main/java/com/ktb/cafeboo/global/apiPayload/exception/ApiExceptionHandler.java
- src/main/java/com/ktb/cafeboo/global/config/SecurityConfig.java
- src/main/java/com/ktb/cafeboo/global/enums/LoginType.java
- src/main/java/com/ktb/cafeboo/global/enums/UserRole.java
- src/main/java/com/ktb/cafeboo/global/security/JwtProvider.java
-`POST /api/v1/auth/guest`: GUEST 계정 생성 및 로그인 API 추가
- `UserRole`, `LoginType`에 GUEST 타입 도입
- GUEST 유저 권한 분리: `@PreAuthorize("hasRole('USER')")`로 일반 유저 API 보호
- `GuestCleanupScheduler` : 매일 오전 10시 게스트 유저 삭제 스케줄러
- GUEST 유저의 접근 제한 정책이 적절한지 피드백 주시면 감사하겠습니다
- 비회원 로그인 후 접근 가능한 API 호출 테스트
- `@PreAuthorize` 적용된 API 접근 시 403 응답 여부 확인
- 하루 이상 지난 GUEST 유저가 자동 삭제되는지 로그 및 DB 상태 확인
Closed:  #231
> [FEAT] 비회원(GUEST) 사용자 기능 도입

- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/ChatService.java
- src/main/java/com/ktb/cafeboo/global/config/RedisConfig.java
Redis Stream은 Consumer Group에 속한 여러 Consumer가 존재할 경우, 해당 그룹의 각 메시지를 그 중 단 한 명의 Consumer에게만 분배합니다.
이 방식은 Pub/Sub처럼 모든 구독자에게 메시지를 브로드캐스트하는 구조가 아닌, Work Queue 방식으로 동작합니다.
이로 인해 하나의 채팅방에 여러 Consumer가 등록되면 메시지가 분산되어 일부 사용자에게 도달하지 않는 문제가 발생합니다.
따라서 채팅방마다 하나의 고정된 Consumer를 등록하고, 해당 Consumer가 수신한 메시지를 서버가 WebSocket을 통해 모든 참여자에게 중계하는 방식으로 구조를 수정했습니다.
- RedisConfig에서 UUID 기반 consumerName 생성 로직 제거
- ChatService 내 startListeningToCoffeeChat()에서 roomId 기반으로 consumerName 생성
- 동일 채팅방에 대해 서버 인스턴스 간 Consumer 중복 생성 방지
- Redis Stream 구독 구조 변경에 따른 side effect 가능성이 있습니다.
- 실제 개발 환경에 먼저 배포하여 의도대로 동작하는지 확인하고, vm이 두개인 환경에서의 테스트가 추가로 필요합니다.
> [FIX] 채팅방별 고정 Consumer 이름 적용으로 메시지 누락 방지

- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/CoffeeChatService.java
- 커피챗 참여 서비스 로직 수정 
- `EVENT` 상태 채팅방도 유효한 참여 대상으로 허용
- x
> [FIX] 이벤트 채팅방 참여 오류 수정

- src/main/java/com/ktb/cafeboo/domain/coffeechat/service/ChatService.java
: 각 채팅방에 대해 단독 Consumer Group을 생성하는 방식 대신, 브로드캐스트 기반의 단순 소비 방식(XREAD)으로 전환
- `streamMessageListenerContainer.register()`를 사용한 XREADGROUP 기반 리스너 등록 방식 제거
- 대신 `streamMessageListenerContainer.receive()`를 사용하여 XREAD 방식으로 적용
- #241 에서 제안주신 내용 그대로 적용하였으나, 
구독 시 수신할 메세지 위치 지정해주는 부분을 `ReadOffset.lastConsumed()` 대신 `ReadOffset.latest()` 으로 수정하였습니다.
구분 | ReadOffset.lastConsumed() | ReadOffset.latest()
-- | -- | --
주 사용처 | XREADGROUP 전용 | XREAD, XREADGROUP 공통
의미 | 해당 Consumer가 마지막으로 읽은 이후 메시지부터 읽기 | 스트림에 새로 들어올 메시지만 읽기
동작 방식 | PEL(Pending Entries List)에 기록된 이후 메시지 | 현재 시점 이후의 메시지만 읽음
- `XREAD` 에서는 소비 상태를 추적하지 않기 때문에 `lastConsumed()`가 무의미하며,
기존 메세지는 채팅방 진입 시 별도의 Rest API를 통해 불러오기 때문에, 새로 들어오는 메세지만 수신하면 됩니다.
따라서, `latest()`를 적용하였습니다.
Fixes: #238 
Closed: #241
> [FIX]: Redis Stream 구독 방식 변경
